services:
  npm:
    container_name: npm
    image: "jc21/nginx-proxy-manager:2.12.3"
    restart: unless-stopped
    networks:
      - focela-network
    depends_on:
      npm-db:
        condition: service_healthy
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /home/data/npm/data:/data
      - /home/data/npm/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: ${DB_MYSQL_HOST:-npm-db}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT:-3306}
      DB_MYSQL_USER: ${DB_MYSQL_USER:-npm}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME:-npm-production}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD:-npmPassword}

  npm-db:
    container_name: npm-db
    image: "jc21/mariadb-aria:latest"
    restart: unless-stopped
    networks:
      - focela-network
    volumes:
      - /home/data/npm/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-npm-production}
      MYSQL_USER: ${MYSQL_USER:-npm}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-npmPassword}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-npmRootPassword}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      start_period: 10s
      retries: 5

networks:
  focela-network:
    driver: bridge
    name: focela-network
